spring:
  profiles:
    active: dev
  application:
    name: AgileFlow.backend
  datasource:
    hikari:
      maximum-pool-size: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate:
      #ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
